package: yform_standalone_validator
version: '1.0.2'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_standalone_validator

requires:
    redaxo: '^5.9'
    php: '>=7.1'
    yform: '>2,<4'
