package: yform_standalone_validator
version: '1.1.0'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/yform_standalone_validator

requires:
    redaxo: '^5.9'
    php: '>=8.0'
    yform: '^4,<5'